name: bonkcoin
# Running 'snapcraft register <name>' is advised
version: '1.1.0'
summary: Reference client of Bonkcoin, a peer-to-peer digital currency like Bitcoin.
description: |
  Bonkcoin is a community-driven cryptocurrency that was inspired by Dogecoin. The Bonkcoin Core software allows anyone to operate a node in the Bonkcoin blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.

grade: stable
confinement: strict
base: core22
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64
  - build-on: i386
    build-for: i386

apps:
  d:
    command: bin/bonkcoind
    plugs: [home, removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at ~/snap/bonkcoin-core/common/.bonkcoin/ instead of ~/snap/bonkcoin-core/current/.bonkcoin/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command-chain: [bin/desktop-launch]
    command: bin/bonkcoin-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: bin/bonkcoin-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  tx:
    command: bin/bonkcoin-tx
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  test:
    command: bin/test_bonkcoin
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  desktop-qt5:
    # So desktop-launch from qt5 is usable
    # Adapted from https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    source-commit: ec861254c2a1d2447b2c589446e6cdf04c75c260
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - fonts-ubuntu
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - libgtk2.0-0
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  bonkcoin:
    plugin: nil
    override-build: |
      echo "This script is viewable at https://github.com/Bonkcoin/bonkcoin/blob/master/contrib/snap/snapcraft.yaml"
      echo "Downloading files..."
      if [ "$CRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but bonkcoin designates it as i686
        BUILD_ARCH_TRIPLET=i686-pc-linux-gnu
      else
        BUILD_ARCH_TRIPLET=$CRAFT_ARCH_TRIPLET
      fi
      wget https://github.com/Bonkcoin/bonkcoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/bonkcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      wget https://github.com/Bonkcoin/gitian.sigs/archive/refs/heads/master.tar.gz
      tar -xvf master.tar.gz
      echo "Verifying secure hash matches signed values..."
      checksum=$(sha256sum bonkcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
      if ! (grep -r $checksum * | grep bonkcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
        echo "Secure hash not verified."
        return
      else
        echo "Secure hash verified."
      fi
      tar -xvf bonkcoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      echo "Running tests..."
      if ! (bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_bonkcoin); then
        echo "Bonkcoin tests failed."
        return
      else
        echo "Bonkcoin tests passed."
      fi
      wget https://raw.githubusercontent.com/Bonkcoin/bonkcoin/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
      cat release-notes.md
      echo "Installing Bonkcoin Core..."
      echo "Version ${SNAPCRAFT_PROJECT_VERSION}"
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/bonkcoind
      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official bonkcoin-qt build on arm64
        install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/bonkcoin-qt
      fi
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/bonkcoin-cli
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/bonkcoin-tx
      install -m 0755 -D -t $CRAFT_PART_INSTALL/bin bonkcoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_bonkcoin
      wget https://raw.githubusercontent.com/Bonkcoin/bonkcoin/master/share/pixmaps/bonkcoin128.png
      install -m 0644 -D -t $CRAFT_PART_INSTALL/share/pixmaps bonkcoin128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
